# Generated by Django 3.0.7 on 2020-06-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='post',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
