# Generated by Django 3.0.6 on 2020-06-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200606_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
