# Generated by Django 3.0.6 on 2020-06-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='grade',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='grade',
            field=models.TextField(default=0),
        ),
    ]
