# Generated by Django 3.0.6 on 2020-06-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200606_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grade',
            field=models.TextField(default=0.1),
        ),
    ]
