# Generated by Django 3.0.6 on 2020-06-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200606_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='grade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='grade',
            field=models.FloatField(default=0),
        ),
    ]
